# Site settings
title: Inner West Damp | Rising damp and sub floor ventilation.
email: info@innerwestdamp.com
description: "Inner west damp specialise in rising damp solutions and sub-floor ventilation for your home or business. We are located in the inner west of sydney covering areas including drummoyne, glebe and marrickville. Call us today for a free quote."
meta_keywords: "rising damp sydney, sub-floor ventilation, damp course, sub floor vents, air vents, dryzone, damp course, sub floor fans, mould removal."
baseurl: ""
url: "http://innerwestdamp.com.au"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
